import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import "@nwaycorp/global-designsystem/core.css";
import "@nwaycorp/global-designsystem/theme.css";
import {
  ContainerModalProvider,
} from "@nwaycorp/global-designsystem";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ContainerModalProvider>
            <div
              style={{
                height: "100dvh",
                maxWidth: "640px",
                minWidth: "320px",
                margin: "0 auto",
                background: "#ffffff",
              }}
            >
              {children}
            </div>
          </ContainerModalProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

// 루트 레이아웃은 모든 페이지에 기본적으로 있다.
// 특정 페이지의 레이아웃만 커스텀하고 싶다면 그 폴더에 layout 파일을 만들면 됨
// RootLayout -> HomeLayout -> HomePage
