import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@nwaycorp/global-designsystem/core.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>루트 레이아웃{children}</body>
    </html>
  );
}

// 루트 레이아웃은 모든 페이지에 기본적으로 있다.
// 특정 페이지의 레이아웃만 커스텀하고 싶다면 그 폴더에 layout 파일을 만들면 됨
// RootLayout -> HomeLayout -> HomePage
